#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ollama"
name = "Ollama"
description.en = "Get up and running with large language models"
description.fr = "Lancez-vous avec les grands modèles de langage"

version = "0.20.5~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
website = "https://ollama.com/"
code = "https://github.com/ollama/ollama"
cpe = "cpe:2.3:a:ollama:ollama"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "2G"
ram.build = "50M"
ram.runtime = "4G"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]

    amd64.url = "https://github.com/ollama/ollama/releases/download/v0.20.5/ollama-linux-amd64.tar.zst"
    amd64.sha256 = "297fd50c2349b8bc83f5c87eae757381c1532c10fe0a813064e6814cdb9c90bb"
    
    arm64.url = "https://github.com/ollama/ollama/releases/download/v0.20.5/ollama-linux-arm64.tar.zst"
    arm64.sha256 = "b1640be9b77ff40b2798e3023c93d66b25011e9a411d18dee1f560a4d2f7e560"
    
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*linux-amd64.tar.zst"
    autoupdate.asset.arm64 = ".*linux-arm64.tar.zst"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["models"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 11434
    main.fixed = true
